
export const ACTION_BACK = 'Navigation/BACK';

export const ACTION_LOGOUT = 'ACTION_LOGOUT';

export const ACTION_USERNAME_CHANGED = 'ACTION_USERNAME_CHANGED';
export const ACTION_PASSWORD_CHANGED = 'ACTION_PASSWORD_CHANGED';
export const ACTION_AUTH_REQUEST = 'ACTION_AUTH_REQUEST';
export const ACTION_AUTH_REQUEST_SUCCESS = 'ACTION_AUTH_REQUEST_SUCCESS';
export const ACTION_AUTH_REQUEST_FAILURE = 'ACTION_AUTH_REQUEST_FAILURE';
export const ACTION_AUTH_SAVED_CREDENTIALS = 'ACTION_AUTH_SAVED_CREDENTIALS';
export const ACTION_AUTH_CREDENTIALS_AVAILBLE = 'ACTION_AUTH_CREDENTIALS_AVAILBLE';


export const ACTION_EVENT_DETAILS = 'ACTION_EVENT_DETAILS';

export const ACTION_EVENTS_LIST_REQUEST = 'ACTION_EVENTS_LIST_REQUEST';
export const ACTION_EVENTS_LIST_REQUEST_SUCCESS = 'ACTION_EVENTS_LIST_REQUEST_SUCCESS';
export const ACTION_EVENTS_LIST_REQUEST_FAILURE = 'ACTION_EVENTS_LIST_REQUEST_FAILURE';
export const ACTION_EVENTS_CONFIRM = 'ACTION_EVENTS_CONFIRM';
export const ACTION_EVENTS_CANCEL = 'ACTION_EVENTS_CANCEL';
export const ACTION_EVENTS_DONE = 'ACTION_EVENTS_DONE';


export const ACTION_NAVIGATE_TO_EVENTS_LIST = 'ACTION_NAVIGATE_TO_EVENTS_LIST ';
export const ACTION_NAVIGATE_TO_INTRO = 'ACTION_NAVIGATE_TO_INTRO ';
export const ACTION_NAVIGATE_TO_LOGIN = 'ACTION_NAVIGATE_TO_LOGIN ';

